### PR TITLE
Upgrade for Angular 9

### PR DESCRIPTION
**Pull request by henrahmagix**
Followed official upgrade instructions https://update.angular.io/#8.0:9.0l3 and did a bit of pruning

### CODE REVIEW

**Comment by alecdewitz** [comment]
Any plans to merge this soon? @willshowell

**Comment by pgkehle** [comment]
We had been trying to keep them at a base level, not to versions > `x.0.0`.  Can you please back them down to 9.0.0 as applicable?

**Comment by pgkehle** [comment]
Also, I tried building locally w/ no success.  What version of node?

**Comment by julianobrasil** [comment]
> Also, I tried building locally w/ no success. What version of node?

@pgkehle and @henrahmagix, apparently it has something to do with this line in `tsconfig.ts`: `"module": "ESNext"`, as it's stated on https://github.com/TypeStrong/ts-node#syntaxerror

Changing that line to `"module": "CommonJS"`, as recommended on the link above, has solved the building problem for me after rebasing this PR to solve the `package-lock.json` conflicts.

**Comment by julianobrasil** [comment]
Man... I accidentally deleted my last post 😄.

> Also, I tried building locally w/ no success. What version of node?

@pgkehle and @henrahmagix, by switching `"module": "ESNext"` to `"module": "CommonJS"` in `tsconfig.json` allowed me to successfully build the project (after rebasing it and solving that `package-lock.json` conflict). You can see some explanation here: https://github.com/TypeStrong/ts-node#syntaxerror

I'm using node v13.10.1

**Comment by pgkehle** [comment]
@julianobrasil do you get any warnings/errors in the demo?  Mine builds and runs now, but I get these warnings:

```
There is no directive with "exportAs" set to "satPopoverAnchor"
'sat-popover' is not a known element:
```

Also, `npm run lint`:
```
> @ncstate/sat-popover@4.0.0 lint /Users/pgkehle/code/popover-h
> ng lint popover --type-check

Linting "popover"...

WARNING: /Users/pgkehle/code/popover-h/src/lib/popover/popover-anchoring.service.ts:280:31 - keyCode is deprecated.
WARNING: /Users/pgkehle/code/popover-h/src/lib/popover/popover.component.ts:308:32 - FocusTrapFactory is deprecated: Use `ConfigurableFocusTrapFactory` instead.
```

**Comment by julianobrasil** [comment]
I haven't run anything yesterday, but I'll mess a little bit with it. One thing that I've noticed by running the demo (`npm run demo`) is that, in `anchor-reuse.component.ts`, you need to change a little bit the `@ViewChild()` statements on these lines:

https://github.com/ncstate-sat/popover/blob/35a99eb3699581e4f023d094248b65a2cb85d156/src/demo/app/anchor-reuse/anchor-reuse.component.ts#L39-L40

 I looks like something changed in angular 9 and you now need to run the queries before the first change detection cycle, or you will have trouble here when calling `getActivePopover()` before the queries have been executed internally by angular:

https://github.com/ncstate-sat/popover/blob/35a99eb3699581e4f023d094248b65a2cb85d156/src/demo/app/anchor-reuse/anchor-reuse.component.ts#L23-L30

You can solve that by just setting the `static` property to true on `@ViewChild()`:

```ts
  @ViewChild('a', {static: true}) aPopover: SatPopover;
  @ViewChild('b', {static: true}) bPopover: SatPopover;
``` 

I'll dig in the other things you've pointed out.

**Comment by Pes8** [comment]
WHEN

**Comment by julianobrasil** [comment]
@pgkehle, concerning the first warning message about the `keyCode` in `popover-anchoring.service.ts`, well, it's a known issue that angular team has chosen to not change until they stop supporting IE11 (see https://github.com/angular/components/issues/7374#issuecomment-467796912). We can just avoid that message by disabling the lint check for that line:

Instead of:

https://github.com/ncstate-sat/popover/blob/35a99eb3699581e4f023d094248b65a2cb85d156/src/lib/popover/popover-anchoring.service.ts#L280

We can just:
```ts
// TODO: remove this line when angular stop supporting IE11 and cdk provides
//   other methods to check for the key codes in a safe way.
// tslint:disable-next-line: deprecation
filter(event => event.keyCode === ESCAPE),
```

**Comment by julianobrasil** [comment]
@pgkehle, the second warning is about an update of cdk a11y API. Originally there was a `FocusTrapFactory.create()` method, which is now deprecated in favor of [`ConfigurableFocusTrapFactory.create()` method](https://github.com/angular/components/blob/239e01d4369b6a838200ea3198277c7bd314859d/src/cdk/a11y/focus-trap/configurable-focus-trap-factory.ts#L49-L53).

The basic difference is that the deprecated one received a boolean as its second parameter:

```ts
create(element: HTMLElement, deferCaptureElements: boolean = false): ConfigurableFocusTrap {
  ...
}
```

The new `ConfigurableFocusTrap.create`, instead of a boolean, receive a `ConfigurableFocusTrapConfig` object:

```ts
/**
   * Creates a focus-trapped region around the given element.
   * @param element The element around which focus will be trapped.
   * @param config The focus trap configuration.
   * @returns The created focus trap instance.
   */
  create(element: HTMLElement, config?: ConfigurableFocusTrapConfig): ConfigurableFocusTrap;
```

As you can see, the second argument is optional, and, internally, its default value is `{defer: false}`.

We are not using the second parameter and the default value is still false for the deferring thing:

https://github.com/ncstate-sat/popover/blob/35a99eb3699581e4f023d094248b65a2cb85d156/src/lib/popover/popover.component.ts#L398

By switching `FocusTrapFactory` to `ConfigurableFocusTrapFactory`, the current unit tests pass. So I think it's safe to switch classes.

**Comment by julianobrasil** [comment]
What do you thinking we should do now? Should we wait for @henrahmagix to fix all of the issues in this single PR?

Or, as an alternative, he could just fix the rebasing and the `"module": "CommonJS"`. The warning about  `FocusTrapFactory` would be taken care of in a tiny separate PR.

**Comment by julianobrasil** [comment]
> @julianobrasil do you get any warnings/errors in the demo? Mine builds and runs now, but I get these warnings:
> 
> There is no directive with "exportAs" set to "satPopoverAnchor"
> 'sat-popover' is not a known element:

I think you're referring to the IDE's warnings (I didn't get this warning on the command line and I think it's just something related to `@angular/language-service`). They go away if you step back from using Ivy in development typescript configs (Ivy is not recommended for libraries development anyway) in `tsconfig.lib.ts`.

```json
"angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": false <= added
},
```

## npm run build (with Ivy):

image

## npm run build (w/o Ivy):

image

## npm run build:demo

image

## npm run demo

image

## npm run test:once

image

**Comment by pgkehle** [comment]
@julianobrasil Yes, I was referring to the IDE warnings in vs-code.  If it is related just to the IDE, which it seems you just proved, then while it would be nice to find a solution for vs-code, it's not something we need to worry about.   

Thanks for all of that digging.  I'd agree that we should get this PR merged then do a smaller follow up for the bugs, like you suggested.  While @willshowell and I were trying to keep this on the major change revision, it's just going to have to be a major release for this project.  

@henrahmagix Can you please submit the change to using `CommonJS` today, and we'll get this merged?

**Comment by pgkehle** [comment]
Obsoleted by #185

**Pull request closed without merging**
